version: '3.8'

services:
  agent_thinking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent_thinking
    env_file:
      - .env
    environment:
      - POETRY_NO_INTERACTION=1
      - POETRY_VIRTUALENVS_CREATE=false
      - POETRY_CACHE_DIR=/var/cache/pypoetry
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
    entrypoint: ["./entrypoint.sh"]
    # command: ["poetry", "run", "python", "-m", "gpt_agent"]
    command: ["poetry", "run", "uvicorn", "gpt_agent.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]